<?php
/**
 * NeoNews Membership v2 — expanded settings defaults.
 *
 * @return array
 */
function neonews_membership_default_settings() {
    return array(
        'enable_paywall'             => true,
        'free_article_limit'         => 5,
        'free_article_period'        => 'month',
        'premium_excerpt_length'     => 150,
        'enable_blur_lock'           => true,
        'lock_blur_strength'         => 6,
        'hide_ads_for_premium'       => true,
        'show_badge_on_avatar'       => true,
        'show_tag_profile'           => true,
        'show_tag_account'           => true,
        'show_badge_comments'        => true,
        'basic_badge_label'          => __( 'Basic', 'neonews-membership' ),
        'basic_tag_label'            => __( 'Basic Plan', 'neonews-membership' ),
        'premium_badge_label'        => __( 'Premium', 'neonews-membership' ),
        'premium_badge_image_id'     => 0,
        'basic_badge_image_id'       => 0,
        'premium_tag_label'          => __( 'Premium Plan', 'neonews-membership' ),
        'key_default_duration_days'  => 30,
        'key_prefix'                 => 'NN',
        'enroll_note'                => __( 'You need an activation key to become a premium member. Contact our team for payment details — we will send your key after manual verification.', 'neonews-membership' ),
        'plan_title'                 => __( 'Premium Membership', 'neonews-membership' ),
        'plan_price'                 => __( 'Contact us for pricing', 'neonews-membership' ),
        'plan_features'              => "Unlimited exclusive articles\nAd-free reading\nEarly access to premium stories\nPriority support",
        'contact_email'              => '',
        'contact_whatsapp_number'    => '',
        'whatsapp_enroll_message'    => __( 'Hello, I would like to enroll in the premium membership plan.', 'neonews-membership' ),
        'email_enroll_subject'       => __( 'Premium membership inquiry', 'neonews-membership' ),
        'email_enroll_body'          => __( 'Hello, I would like to subscribe to the premium plan. Please share payment details and my activation key.', 'neonews-membership' ),
        'expiry_reminder_days'       => 10,
        'show_expiry_timer_profile'  => true,
        'show_expiry_timer_account'  => true,
        'show_expiry_icon_header'    => true,
        'enable_upgrade_popup'       => true,
        'popup_delay_seconds'        => 45,
        'popup_interval_hours'       => 24,
        'popup_title'                => __( 'Become a Premium Member', 'neonews-membership' ),
        'popup_message'              => __( 'Unlock exclusive stories and the latest content without ads. Get your activation key from our team after payment.', 'neonews-membership' ),
        'exclusive_page_slug'        => 'exclusive',
        'show_home_premium_section'  => true,
        'home_premium_count'         => 4,
        'home_premium_title'         => __( 'Premium Picks', 'neonews-membership' ),
        'exclusive_page_count'       => 12,
        'exclusive_page_subtitle'    => __( 'Premium stories for members — unlock full access with a plan.', 'neonews-membership' ),
        'exclusive_badge_label'      => __( 'Exclusive', 'neonews-membership' ),
        'exclusive_card_layout'      => 'rich',
        'exclusive_card_style'       => 'elevated',
        'exclusive_show_category'    => true,
        'exclusive_show_excerpt'     => true,
        'exclusive_show_author'      => true,
        'exclusive_show_date'        => true,
        'exclusive_show_reading_time'=> true,
        'exclusive_show_views'       => true,
        'exclusive_show_views_overlay' => true,
        'exclusive_show_likes'       => true,
        'exclusive_show_comments'    => true,
        'exclusive_show_engagement'  => true,
        'exclusive_excerpt_words'    => 20,
        'stripe_mode'                => 'test',
        'stripe_test_public_key'     => '',
        'stripe_test_secret_key'     => '',
        'stripe_live_public_key'     => '',
        'stripe_live_secret_key'     => '',
        'payment_gateway_enabled'    => false,
    );
}
